#vars:
# NB: change the following to reflect your server's disk naming
disk0: /dev/vda
disk1: /dev/vdb
disk2: /dev/vdc
# NB: change to false if you do not want to use the docker project's repo. this means you have docker on an internal repo
install_docker_repo: false
# NB: leave blank if you do not use a proxy in your environment
proxy_env:
  http_proxy: http://$IP:$Port
  https_proxy: https://$IP:$PORT
