#vars:
# NB: change the following to reflect your server's disk naming
#4disk0: /dev/vda
#4disk1: /dev/vdb
#4disk2: /dev/vdc


disk0: /dev/xvda
disk1: /dev/xvdc
disk2: /dev/xvde

# NB: change to false if you do not want to use the docker project's repo. this means you have docker on an internal repo
install_docker_repo: true
# NB: leave blank if you do not use a proxy in your environment
proxy_env:
  http_proxy: http://$IP:$Port
  https_proxy: https://$IP:$PORT
docker_version: 1.12.1-1.el7.centos
#docker_Version: 1.9.0
