---
  - hosts: all
    tasks:
    gather_facts: true
    become: yes
    become_method: sudo 
    vars:
      disk0: /dev/xvda
      disk1: /dev/xvdc
      disk2: /dev/xvde
      install_docker_repo: true
      proxy_env:
        http_proxy: http://10.140.132.213:3128
        https_proxy: https://10.140.132.213:3128
    roles:
# from installation guide
      - installation_checks
      - installation_network
      - installation_logs
      - installation_selinux
      - installation_filesystems
      - installation_check_docker_dir
      - installation_repos
      - installation_check_docker_dir
      - installation_serviced
      - installation_services
      - installation_check_docker_dir
      - installation_docker-config
      - installation_check_docker_dir
      - installation_complete
# from configuration guide
      - config_zrm-config
