---
  - hosts: all
    tasks:
    gather_facts: true
    sudo: yes
    roles:
# from installation guide
      - checks
      - network
      - logs
      - selinux
      - filesystems
      - check_docker_dir
      - repos
      - check_docker_dir
      - serviced
      - services
      - check_docker_dir
      - docker-config
      - check_docker_dir
      - complete
# from configuration guide
      - zenoss-config
