---
- hosts: all
  tasks:
  - name: Disable Firewall
    service: name=firewalld state=stopped enabled=false
  - name: Disable SELinux
    selinux: state=disabled
  - name: Create BTRFS mountpoints
    file: path={{ item }} state=directory
    with_items:
    - /opt/serviced/var/volumes
    - /var/lib/docker
  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
    - ntp
    - dnsmasq
    - http://get.zenoss.io/yum/zenoss-repo-1-1.x86_64.rpm
  - name: Set Docker default config
    copy: dest=/etc/sysconfig/docker content='DOCKER_OPTS="--dns=172.17.42.1"\n'
  - name: Install Zenoss Core Service
    yum: name=zenoss-core-service enablerepo=zenoss-stable
  - name: Reconfigure NFS
    command: "sed -i -e 's/\\(Requires=.*\\)rpcbind.target/\\1rpcbind.service/' /usr/lib/systemd/system/nfs-server.service"
  - name: Enable services
    service: name={{ item }} state=running enabled=true
    with_items:
    - ntpd
    - dnsmasq
    - docker
    - serviced
  - name: Create BTRFS Filesystem for /var/lib/docker
    filesystem: fstype=btrfs dev=/dev/xvdb
  - name: Mount BTRFS Filesystem for /var/lib/docker
    mount: name=/var/lib/docker src=/dev/xvdb fstype=btrfs state=present
  - name: Create BTRFS Filesystem for /opt/serviced/var/volumes
    filesystem: fstype=btrfs dev=/dev/xvdc
  - name: Mount BTRFS Filesystem for /opt/serviced/var/volumes
    mount: name=/opt/serviced/var/volumes src=/dev/xvdc fstype=btrfs state=present
#  - name: Wait for server to restart
#    command: "/sbin/reboot"
#    sudo: true
  - name: Install Control Center and Resource Manager
    yum: name=zenoss-resmgr-service enablerepo=zenoss-stable
