---
  - hosts: all
    tasks:
    gather_facts: true
    become: yes
    become_method: sudo 
    vars:
# NB: change the following to reflect your server's disk naming
#1      disk0: /dev/xvda
#1      disk1: /dev/xvdc
#1      disk2: /dev/xvde
# NB: change to false if you do not want to use the docker project's repo. this means you have docker on an internal repo
#2      install_docker_repo: false
# NB: leave blank if you do not use a proxy in your environment
      proxy_env:
        http_proxy: http://$IP:$Port
        https_proxy: https://$IP:$PORT
    roles:
# from installation guide
      - installation_checks
      - installation_network
      - installation_logs
      - installation_selinux
      - installation_filesystems
      - installation_docker_copy
      - installation_zenoss  
      - installation_repos
      - installation_serviced
      - installation_services
      - installation_docker-config
      - installation_complete
# from configuration guide
      - config_zrm-config
