---
  - hosts: all
    tasks:
    gather_facts: true
    sudo: yes
    roles:
# - checks
# - network
      - checks
      - network
      - logs
      - selinux
      - filesystems
      - repos
      - serviced
      - services
      - docker-config
      - zenoss-config
      - complete
