---
  - hosts: all
    tasks:
    gather_facts: true
    become: yes
    become_method: sudo 
    vars:
# NB: some variables have moved to group_vars/all.yml
#
# NB: leave blank if you do not use a proxy in your environment
      proxy_env:
        http_proxy: http://$IP:$Port
        https_proxy: https://$IP:$PORT
    roles:
# from installation guide
      - installation_checks
      - installation_network
      - installation_logs
      - installation_selinux
      - installation_filesystems
#copy docker rpms over to the target server
      - role: installation_docker_copy
        when: install_docker_repo == False
#copy images from public to local registry
      - role: installation_containers
        when: install_docker_repo == False
#copy zenoss rpms over to the target server
      - role: installation_zenoss  
        when: install_docker_repo == False
#install from yum repos
      - role: installation_repos
        when: install_docker_repo == True
      - installation_serviced
      - installation_services
      - installation_docker-config
      - installation_complete
# from configuration guide
      - config_zrm-config
