---
  - hosts: all
    tasks:
    gather_facts: true
    become: yes
    become_method: sudo 
    vars:
      disk0: /dev/xvda
      disk1: /dev/xvdc
      disk2: /dev/xvde
    roles:
# from installation guide
#      - debug
      - installation_checks
      - installation_network
      - installation_logs
      - installation_selinux
      - debug
      - installation_filesystems
      - debug
      - installation_check_docker_dir
      - installation_repos
      - installation_check_docker_dir
      - installation_serviced
      - installation_services
      - installation_check_docker_dir
      - installation_docker-config
      - installation_check_docker_dir
      - installation_complete
# from configuration guide
      - config_zrm-config
