--- 
  - name: Copy docker files
    copy: src={{ item }} dest=/tmp/ 
    with_items:
      - docker-engine-1.9.0-1.el7.centos.x86_64.rpm
      - docker-engine-selinux-1.9.0-1.el7.centos.noarch.rpm
    when: install_docker_repo == False

  - name: Install docker from local files
    yum: name=/tmp/{{ item }} state=present
    with_items:
      - docker-engine-1.9.0-1.el7.centos.x86_64.rpm
      - docker-engine-selinux-1.9.0-1.el7.centos.noarch.rpm
    when: install_docker_repo == False

