---
  - name: Install deltarpm
    yum: name=deltarpm state=latest
#    environment: "{{proxy_env}}"

  - name: Configure yum to skip-broken
    lineinfile: dest=/etc/yum.conf line="skip_broken=1"

  - name: Update all packages
    yum: name=* state=latest 
#    environment: "{{proxy_env}}"

  - name: Install packages
    yum: name={{ item }} state=present
#    environment: "{{proxy_env}}"
    with_items:
    - rpcbind
    - nfs-utils
    - ntp
    - dnsmasq

  - name: Install docker {{ docker_version }} from docker repo
    yum: name={{ item }} state=present
    with_items:
    - docker-engine-{{ docker_version }}
    when: install_docker_repo == True

  - name: Install Zenoss repo package
    yum: name={{ item }} state=present
#    environment: "{{proxy_env}}"
    with_items:
    - http://get.zenoss.io/yum/zenoss-repo-1-1.x86_64.rpm
    when: install_docker_repo == True

  - name: Disable Docker repo
    replace: dest=/etc/yum.repos.d/docker.repo regexp='enabled=1' replace='enabled=0'
    when: install_docker_repo == True

  - name: Disable Zenoss repo
    replace: dest=/etc/yum.repos.d/zenoss-stable.repo regexp='enabled=1' replace='enabled=0'
    when: install_docker_repo == True
