---
  - name: Add {{ ansible_fqdn }} to hosts file
    lineinfile: dest=/etc/hosts line="{{ ansible_eth0.ipv4.address}} \t  {{ ansible_fqdn }} \t {{ ansible_hostname }}"
  - name: Add zenoss5.{{ ansible_fqdn }} to hosts file
    lineinfile: dest=/etc/hosts line="{{ ansible_eth0.ipv4.address}} \t  zenoss5.{{ ansible_fqdn }}"
