---
  - name: Start of Zenoss Resource Configuration Guide
    debug: msg="URL https://www.zenoss.com/sites/default/files/documentation/Zenoss_Resource_Manager_Configuration_Guide_r5.1.1_d1042.16.061.1.pdf"

  - name: Warning
    debug: msg="Change default passwords via Control Center"

  - debug: Now pulling container images from docker hub. This could take time depending on your internet connection

  - name: Wait for Control Center to start
    wait_for: port=443 state=started delay=600
