---
  - name: Create BTRFS mountpoints
    file: path={{ item }} state=directory
    with_items:
    - /opt/serviced/var/volumes
    - /var/lib/docker
  - name: Create BTRFS Filesystem for /var/lib/docker on {{ disk1.stat.path }}
    filesystem: fstype=btrfs dev={{ disk1.stat.path }}
  - name: Mount BTRFS Filesystem of {{ disk1.stat.path}} for /var/lib/docker
    mount: name=/var/lib/docker src={{ disk1.stat.path }} fstype=btrfs state=mounted
  - name: Create BTRFS Filesystem for /opt/serviced/var/volumes on {{ disk2.stat.path }}
    filesystem: fstype=btrfs dev={{ disk2.stat.path }}
  - name: Mount BTRFS Filesystem for /opt/serviced/var/volumes on {{ disk2.stat.path }}
    mount: name=/opt/serviced/var/volumes src={{ disk2.stat.path }} fstype=btrfs state=mounted

