--- 
  - name: Copy zenoss rpm files
    copy: src={{ item }} dest=/tmp/ 
    with_items:
      - serviced-1.1.8-1.x86_64.rpm
      - zenoss-core-service-5.1.7-1.noarch.rpm  
      - zenoss-resmgr-service-5.1.7-1.noarch.rpm

  - name: Install zenoss from local files
    yum: name=/tmp/{{ item }} state=present
    with_items:
      - serviced-1.1.8-1.x86_64.rpm
      - zenoss-resmgr-service-5.1.7-1.noarch.rpm
      - zenoss-core-service-5.1.7-1.noarch.rpm  
