---
  - name: Reconfigure NFS
    command: "sed -i -e 's/\\(Requires=.*\\)rpcbind.target/\\1rpcbind.service/' /usr/lib/systemd/system/nfs-server.service"
  - name: Enable services
    service: name={{ item }} state=running enabled=true
    with_items:
    - ntpd
    - dnsmasq
    - docker
    - serviced
#  - name: Wait for server to restart
#    command: "/sbin/reboot"
#    sudo: true
