---
  - name: Set Docker default config
    copy: dest=/etc/sysconfig/docker content='DOCKER_OPTS="-s btrfs--dns={{ ansible_docker0.ipv4.address }}"\n'
  - name: Reconfigure /lib/systemd/system/docker.service
    lineinfile: dest=/lib/systemd/system/docker.service regexp='daemon' line='ExecStart=/usr/bin/docker daemon $OPTIONS -H fd://'
