---
#  - name: Check RAM
#    debug: msg="Continue only if {{ ansible_memory_mb.real.total }} >= 20480"
  - fail: msg="RAM must be equal to or greater than 20480"
    when: ansible_memory_mb.real.total|int < 20480
#    when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 6
